### ISSUE TITLE
Som errors in two cases

### ISSUE THREAD

**Issue by mcfdez** [wodka/angular-magnific-popup#3]
Hello.

I implemented the directive to my app but I get some errors. If I put the tag in the image tag I get this error: TypeError: t.find is not a function

And if I put the tag in a element I get this error: <pre>Error: Syntax error, unrecognized expression: https:/myimage/gnfn.png</pre>

Then, what ways I have to work?

**Comment by Buzzinoffbond** [comment]
You should define content type 
http://dimsemenov.com/plugins/magnific-popup/documentation.html#content-types

Get it work using magnific-popup tag on anchor element with class mfp-TYPE
e.g.

```
<a href="{{Video.url}}" magnific-popup class="mfp-iframe">
    <img src="{{Video.thumb}}">
 </a>
```

**Comment by wodka** [comment]
or pass a type:

``` html
<a href="{{Video.url}}" magnific-popup type="iframe">open video</a>
```
