### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by shinevk** [wodka/angular-magnific-popup#4]
Can you please provide a sample code for implementing this.

**Comment by notfalsedev** [comment]
+1 need a example please

**Comment by chozzz** [comment]
+1 need an example

**Comment by wodka** [comment]
sry for the slow response.

it's really easy: 

if you would have the following call in javascript:

``` javascript
$('.image-link').magnificPopup({ type:'image' });
```

``` html
<a magnific-popup type="image" href="some-image.jpg">open image</a>
```
